### ISSUE TITLE
Support Safari 13

### ISSUE THREAD

**Issue by brainsik** [kryptco/kr-u2f#38] opened 2019-08-24 17:37 UTC
Safari Technology Preview has native support for U2F. It would be great if the Krypton extension could work with this version. Going to the extensions gallery page doesn't show an "install" button.

* [Safari Technology Preview downloads](https://developer.apple.com/safari/download/)
* [Krypton Authenticator extension](https://safari-extensions.apple.com/details/?id=co.krypt.krypton.u2f-W7AMYM5LPN)

**Comment by apburgess** [comment] 2019-09-05 09:18
+1 -- Especially as the upcoming version of Safari for macOS Catalina and the next version of Safari for Mojave won't support the old Safari extension system either.

**Comment by agrinman** [comment] 2019-10-09 04:03
We're working on a new macOS app that brings support to safari 13 (and any other browser, without a browser extension). If you're interested in access to the beta, signup is here: https://forms.gle/4keW9m86sFadxtEi6

**Comment by vzhilov** [comment] 2019-10-09 10:37
Is this going to be for Safari 13 on iPadOS as well?

**Comment by dspaxton** [comment] 2020-02-06 08:17
whats the status of this issue? i signed up for the beta when i saw the link but it appears nothing is happening

**Comment by ryoppippi** [comment] 2020-02-10 02:47
Me neither 
Please respond to our signup

**Comment by drcongo** [comment] 2020-02-28 15:49
I'm starting to worry that the Kryptonite team have all been locked in a cupboard at Akamai

**Comment by dspaxton** [comment] 2020-02-28 18:22
> I'm starting to worry that the Kryptonite team have all been locked in a cupboard at Akamai

the lack of activity here would seem to confirm that supposition

**Comment by drcongo** [comment] 2020-03-04 13:36
Such a shame, I _love_ Kryptonite.

**Comment by agrinman** [comment] 2020-05-08 21:07
Sorry for the delay here! Our macOS app needs access to the new DriverKit entitlement from apple as we'll need to utilize a user-space kernel extension (for universal browser support).

HOWEVER! We decided to just release Safari-app extension macOS app for Krypton so while we get the above working, **Krypton users will still be able to have solid Safari support**.

It's currently in review in the mac app store, so please stay tuned in the next couple of days we'll be able to push this out.

**Comment by agrinman** [comment] 2020-05-08 23:59
Another update: will release on the app store soon.
In the mean time, here's a signed build you can download and use now: [**Download Krypton for Mac**](https://keybase.pub/agrinman/downloads/KryptonForMac.zip)

**Comment by lumaxis** [comment] 2020-05-09 00:02
@agrinman Fantastic to see you active again here 🙂

**Comment by agrinman** [comment] 2020-05-10 00:26
https://apps.apple.com/us/app/krypton-authenticator-desktop/id1512484779?ls=1

**Comment by agrinman** [comment] 2020-05-10 00:27
Please test it out and let me know if there are any issues :)

**Comment by pugthelouie** [comment] 2020-05-11 03:04
Thank you so much! I've been waiting for this for ages :)

**Comment by pugthelouie** [comment] 2020-05-11 03:22
Hmm. 
Seems Google doesn't want to play nice. Any insights?

![https://imgur.com/afJCiDV](https://imgur.com/afJCiDV)
Otherwise, really good work on the new extension. I never knew how much I missed the zero-touch logins until now.

**Comment by pugthelouie** [comment] 2020-05-11 03:30
Also seems to have created a ghost GitHub in my Krypton app. Odd.

![image](https://user-images.githubusercontent.com/16177268/81521781-3d959c00-9316-11ea-9c53-035aac72d229.jpeg)

**Comment by agrinman** [comment] 2020-05-11 03:31
@pugthelouie can you create a separate issue for these?

**Comment by pugthelouie** [comment] 2020-05-11 03:32
Sure! Hold on.

**Comment by pugthelouie** [comment] 2020-05-11 03:35
I presume the iOS app's duplicate entry bug should go in [kryptco/krypton-ios](https://github.com/kryptco/krypton-ios)

**Comment by agrinman** [comment] 2020-05-11 03:37
Yeah -- this is because GitHub upgraded from U2F to WebAuthn, hence Krypton iOS treats that as a different appid -- well, because it is, and doesn't know (yet) to map them to the same service. Easy fix, but will come a bit later as it's just cosmetic.

**Comment by pugthelouie** [comment] 2020-05-11 03:38
Alright. I opened the issue for future reference- There's the other Google one in this repo at #45

**Comment by pugthelouie** [comment] 2020-05-11 04:25
Oh and- Will this new app be open sourced?

**Comment by agrinman** [comment] 2020-05-11 04:26
Public sourced soon, TBD on "open"

**Comment by drcongo** [comment] 2020-05-11 07:59
Installed from the Mac App Store, I get this...

<img width="532" alt="Screen Shot 2020-05-11 08 58 28 AM" src="https://user-images.githubusercontent.com/39289/81537776-a1938100-9365-11ea-91d7-6b6eb9ec24bb.png">

And there's no sign of a Krypt Safari extension in my Safari's extensions, have I messed this up?

**Comment by agrinman** [comment] 2020-05-11 14:38
@drcongo looks like a few users are getting this..very strange. Can you quite safari and restart it?

**Comment by agrinman** [comment] 2020-05-11 15:00
@drcongo are you on 10.15 or and older macOS?

**Comment by drcongo** [comment] 2020-05-11 15:01
Hey @agrinman, I've tried that a few times. Let me know if there's log files or anything I can send over to help you debug it.

I'm on 10.14.6 (with no plans on upgrading to Catalina)
Safari version  13.1 (14609.1.20.111.8)

**Comment by agrinman** [comment] 2020-05-11 16:17
Yep looks like this is a 10.14.6 issue. Will try to push a fix soon, I can post a pre-release build here so it would be great if you could test it out on your system.

**Comment by drcongo** [comment] 2020-05-11 16:30
Happy to help @agrinman, I've missed having Kryptonite in Safari.

**Comment by agrinman** [comment] 2020-05-12 13:32
@drcongo Just released [v1.1](https://apps.apple.com/us/app/krypton-authenticator-desktop/id1512484779?ls=1) on the  macOS App Store that should fix this problem

**Comment by drcongo** [comment] 2020-05-12 15:02
@agrinman Confirmed working here, nice work sir!

**Comment by agrinman** [comment] 2020-05-12 15:04
Closing now that [Krypton's new Safari macOS app](https://apps.apple.com/us/app/krypton-authenticator-desktop/id1512484779?ls=1) extension is live and seems to work for folks.

Please open any issues with Safari as new github issues. Thanks!

**Closed by agrinman** 2020-05-12 15:04 UTC
